import JSZip from "jszip";

interface ESXData {
  jobId: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  inspectionDate: string;
  claimNumber?: string;
  findings: {
    damage_type: string;
    severity: string;
    confidence: number;
    notes?: string | null;
  }[];
  measurements?: {
    areaSqft: number;
    perimeterFt: number;
    estimatedSquares: number;
  } | null;
}

const XACT_CATEGORY_MAP: Record<string, { category: string; selector: string; unit: string }> = {
  missing_shingle: { category: "RFG", selector: "RFGSHCOMP", unit: "SF" },
  hail: { category: "RFG", selector: "RFGSHCOMP", unit: "SF" },
  wind: { category: "RFG", selector: "RFGSHCOMP", unit: "SF" },
  granule_loss: { category: "RFG", selector: "RFGSHCOMP", unit: "SF" },
  cracking: { category: "RFG", selector: "RFGSHCOMP", unit: "SF" },
  flashing_damage: { category: "RFG", selector: "RFGFLALUM", unit: "LF" },
  impact: { category: "RFG", selector: "RFGSHCOMP", unit: "SF" },
  ponding: { category: "RFG", selector: "RFGSHCOMP", unit: "SF" },
  debris: { category: "RFG", selector: "RFGDEBRIS", unit: "SF" },
  mechanical: { category: "RFG", selector: "RFGSHCOMP", unit: "SF" },
  other: { category: "RFG", selector: "RFGSHCOMP", unit: "SF" },
};

function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function generateProjectXml(data: ESXData): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<ESX version="4.0">
  <ProjectInfo>
    <ProjectName>Inspection - ${escapeXml(data.address)}</ProjectName>
    <ClaimNumber>${escapeXml(data.claimNumber || data.jobId.slice(0, 8).toUpperCase())}</ClaimNumber>
    <DateOfLoss>${data.inspectionDate}</DateOfLoss>
    <DateInspected>${data.inspectionDate}</DateInspected>
    <TypeOfLoss>STORM</TypeOfLoss>
    <CatCode></CatCode>
    <PolicyNumber></PolicyNumber>
    <Insured>
      <Name></Name>
      <Address>
        <Street>${escapeXml(data.address)}</Street>
        <City>${escapeXml(data.city)}</City>
        <State>${escapeXml(data.state)}</State>
        <Zip>${escapeXml(data.zip)}</Zip>
      </Address>
    </Insured>
  </ProjectInfo>
  <Estimate>
    <Room name="Roof" type="EXT">
      <Dimensions>
        ${data.measurements ? `
        <Area unit="SF">${data.measurements.areaSqft}</Area>
        <Perimeter unit="LF">${data.measurements.perimeterFt}</Perimeter>
        ` : ""}
      </Dimensions>
      <LineItems>
        ${generateLineItems(data)}
      </LineItems>
    </Room>
  </Estimate>
  <Notes>
    <Note type="General">
      AI-assisted inspection report generated by Apex Drone Solutions.
      ${data.findings.length} damage findings detected with automated analysis.
      ${data.measurements ? `Roof area: ${data.measurements.areaSqft} sqft, ${data.measurements.estimatedSquares} squares.` : ""}
    </Note>
    ${data.findings
      .filter((f) => f.notes)
      .map((f, i) => `
    <Note type="Finding">
      Finding ${i + 1}: ${escapeXml(f.damage_type)} - ${escapeXml(f.severity)} severity (${Math.round(f.confidence * 100)}% confidence)
      ${f.notes ? escapeXml(f.notes) : ""}
    </Note>`).join("")}
  </Notes>
</ESX>`;
}

function generateLineItems(data: ESXData): string {
  // Aggregate findings by type for line items
  const aggregated: Record<string, { count: number; maxSeverity: string; notes: string[] }> = {};

  data.findings.forEach((f) => {
    if (!aggregated[f.damage_type]) {
      aggregated[f.damage_type] = { count: 0, maxSeverity: f.severity, notes: [] };
    }
    aggregated[f.damage_type].count++;
    if (f.notes) aggregated[f.damage_type].notes.push(f.notes);
  });

  const items: string[] = [];

  // R&R Shingles (if any shingle damage found)
  const roofDamageTypes = ["hail", "wind", "missing_shingle", "granule_loss", "cracking", "impact"];
  const hasRoofDamage = roofDamageTypes.some((t) => aggregated[t]);

  if (hasRoofDamage && data.measurements) {
    items.push(`
        <LineItem>
          <Category>RFG</Category>
          <Selector>RFGSHCOMP</Selector>
          <Description>R&amp;R Composition shingle roofing - per square</Description>
          <Quantity>${data.measurements.estimatedSquares}</Quantity>
          <Unit>SQ</Unit>
          <Action>R&amp;R</Action>
          <Notes>AI detected damage: ${roofDamageTypes.filter((t) => aggregated[t]).map((t) => `${t} (${aggregated[t].count})`).join(", ")}</Notes>
        </LineItem>`);
  }

  // Underlayment
  if (hasRoofDamage && data.measurements) {
    items.push(`
        <LineItem>
          <Category>RFG</Category>
          <Selector>RFGFELT15</Selector>
          <Description>Roofing felt - 15 lb.</Description>
          <Quantity>${data.measurements.areaSqft}</Quantity>
          <Unit>SF</Unit>
          <Action>R&amp;R</Action>
        </LineItem>`);
  }

  // Flashing if found
  if (aggregated.flashing_damage && data.measurements) {
    items.push(`
        <LineItem>
          <Category>RFG</Category>
          <Selector>RFGFLALUM</Selector>
          <Description>Flashing - aluminum</Description>
          <Quantity>${Math.round(data.measurements.perimeterFt * 0.3)}</Quantity>
          <Unit>LF</Unit>
          <Action>R&amp;R</Action>
          <Notes>${aggregated.flashing_damage.count} flashing damage findings</Notes>
        </LineItem>`);
  }

  // Drip edge
  if (hasRoofDamage && data.measurements) {
    items.push(`
        <LineItem>
          <Category>RFG</Category>
          <Selector>RFGDRPEDG</Selector>
          <Description>Drip edge</Description>
          <Quantity>${data.measurements.perimeterFt}</Quantity>
          <Unit>LF</Unit>
          <Action>R&amp;R</Action>
        </LineItem>`);
  }

  // Ice and water shield (if hail or wind)
  if ((aggregated.hail || aggregated.wind) && data.measurements) {
    items.push(`
        <LineItem>
          <Category>RFG</Category>
          <Selector>RFGICEWTC</Selector>
          <Description>Ice &amp; water barrier</Description>
          <Quantity>${Math.round(data.measurements.perimeterFt * 3)}</Quantity>
          <Unit>SF</Unit>
          <Action>R&amp;R</Action>
        </LineItem>`);
  }

  // Individual damage-specific items
  Object.entries(aggregated).forEach(([type, info]) => {
    const xactMap = XACT_CATEGORY_MAP[type];
    if (!xactMap) return;

    items.push(`
        <LineItem>
          <Category>${xactMap.category}</Category>
          <Selector>${xactMap.selector}</Selector>
          <Description>${escapeXml(type.replace(/_/g, " "))} - ${info.count} location(s) - ${info.maxSeverity}</Description>
          <Quantity>${info.count}</Quantity>
          <Unit>EA</Unit>
          <Action>NOTE</Action>
          <Notes>${info.notes.slice(0, 3).join("; ").slice(0, 200)}</Notes>
        </LineItem>`);
  });

  return items.join("");
}

export async function generateESXFile(data: ESXData): Promise<Blob> {
  const zip = new JSZip();

  // ESX is a ZIP containing XML files
  zip.file("project.xml", generateProjectXml(data));

  // Manifest
  zip.file("manifest.xml", `<?xml version="1.0" encoding="utf-8"?>
<Manifest version="1.0">
  <Files>
    <File name="project.xml" type="project" />
  </Files>
  <Generator>Apex Drone Solutions</Generator>
  <GeneratedDate>${new Date().toISOString()}</GeneratedDate>
</Manifest>`);

  return await zip.generateAsync({ type: "blob", mimeType: "application/x-esx" });
}
